"""add_performance_indexes

Revision ID: 066921ea38cb
Revises: 1ecaf54ed1a3
Create Date: 2026-07-12 19:16:51.396052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066921ea38cb'
down_revision: Union[str, None] = '1ecaf54ed1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_announcements_apartment_id'), 'announcements', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_apartment_gallery_images_apartment_id'), 'apartment_gallery_images', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_apartments_city_id'), 'apartments', ['city_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_flat_id'), 'bookings', ['flat_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_rules_apartment_id'), 'community_rules', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_complaints_apartment_id'), 'complaints', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_complaints_resident_id'), 'complaints', ['resident_id'], unique=False)
    op.create_index(op.f('ix_complaints_user_id'), 'complaints', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_booking_id'), 'documents', ['booking_id'], unique=False)
    op.create_index(op.f('ix_documents_flat_id'), 'documents', ['flat_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_apartment_id'), 'facility_bookings', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_resident_id'), 'facility_bookings', ['resident_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_user_id'), 'facility_bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_flat_images_flat_id'), 'flat_images', ['flat_id'], unique=False)
    op.create_index(op.f('ix_flats_apartment_id'), 'flats', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_flats_floor_id'), 'flats', ['floor_id'], unique=False)
    op.create_index(op.f('ix_flats_status'), 'flats', ['status'], unique=False)
    op.create_index(op.f('ix_floors_apartment_id'), 'floors', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_flat_id'), 'maintenance', ['flat_id'], unique=False)
    op.create_index(op.f('ix_maintenance_user_id'), 'maintenance', ['user_id'], unique=False)
    op.create_index(op.f('ix_maintenance_bills_flat_id'), 'maintenance_bills', ['flat_id'], unique=False)
    op.create_index(op.f('ix_maintenance_bills_resident_id'), 'maintenance_bills', ['resident_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_rent_records_flat_id'), 'rent_records', ['flat_id'], unique=False)
    op.create_index(op.f('ix_rent_records_resident_id'), 'rent_records', ['resident_id'], unique=False)
    op.create_index(op.f('ix_resident_access_requests_booking_id'), 'resident_access_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_resident_access_requests_customer_id'), 'resident_access_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_resident_access_requests_document_id'), 'resident_access_requests', ['document_id'], unique=False)
    op.create_index(op.f('ix_resident_access_requests_flat_id'), 'resident_access_requests', ['flat_id'], unique=False)
    op.create_index(op.f('ix_residents_apartment_id'), 'residents', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_residents_flat_id'), 'residents', ['flat_id'], unique=False)
    op.create_index(op.f('ix_residents_floor_id'), 'residents', ['floor_id'], unique=False)
    op.create_index(op.f('ix_site_visits_apartment_id'), 'site_visits', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_site_visits_customer_id'), 'site_visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_site_visits_flat_id'), 'site_visits', ['flat_id'], unique=False)
    op.create_index(op.f('ix_vehicles_flat_id'), 'vehicles', ['flat_id'], unique=False)
    op.create_index(op.f('ix_vehicles_resident_id'), 'vehicles', ['resident_id'], unique=False)
    op.create_index(op.f('ix_visitors_flat_id'), 'visitors', ['flat_id'], unique=False)
    op.create_index(op.f('ix_visitors_resident_id'), 'visitors', ['resident_id'], unique=False)
    op.create_index(op.f('ix_wishlists_flat_id'), 'wishlists', ['flat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_flat_id'), table_name='wishlists')
    op.drop_index(op.f('ix_visitors_resident_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_flat_id'), table_name='visitors')
    op.drop_index(op.f('ix_vehicles_resident_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_flat_id'), table_name='vehicles')
    op.drop_index(op.f('ix_site_visits_flat_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_customer_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_apartment_id'), table_name='site_visits')
    op.drop_index(op.f('ix_residents_floor_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_flat_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_apartment_id'), table_name='residents')
    op.drop_index(op.f('ix_resident_access_requests_flat_id'), table_name='resident_access_requests')
    op.drop_index(op.f('ix_resident_access_requests_document_id'), table_name='resident_access_requests')
    op.drop_index(op.f('ix_resident_access_requests_customer_id'), table_name='resident_access_requests')
    op.drop_index(op.f('ix_resident_access_requests_booking_id'), table_name='resident_access_requests')
    op.drop_index(op.f('ix_rent_records_resident_id'), table_name='rent_records')
    op.drop_index(op.f('ix_rent_records_flat_id'), table_name='rent_records')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_maintenance_bills_resident_id'), table_name='maintenance_bills')
    op.drop_index(op.f('ix_maintenance_bills_flat_id'), table_name='maintenance_bills')
    op.drop_index(op.f('ix_maintenance_user_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_flat_id'), table_name='maintenance')
    op.drop_index(op.f('ix_floors_apartment_id'), table_name='floors')
    op.drop_index(op.f('ix_flats_status'), table_name='flats')
    op.drop_index(op.f('ix_flats_floor_id'), table_name='flats')
    op.drop_index(op.f('ix_flats_apartment_id'), table_name='flats')
    op.drop_index(op.f('ix_flat_images_flat_id'), table_name='flat_images')
    op.drop_index(op.f('ix_facility_bookings_user_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_resident_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_apartment_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_documents_flat_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_booking_id'), table_name='documents')
    op.drop_index(op.f('ix_complaints_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_resident_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_apartment_id'), table_name='complaints')
    op.drop_index(op.f('ix_community_rules_apartment_id'), table_name='community_rules')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_flat_id'), table_name='bookings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_apartments_city_id'), table_name='apartments')
    op.drop_index(op.f('ix_apartment_gallery_images_apartment_id'), table_name='apartment_gallery_images')
    op.drop_index(op.f('ix_announcements_apartment_id'), table_name='announcements')
    # ### end Alembic commands ###
